// This file is auto-generated by next-intl, do not edit directly.
// See: https://next-intl.dev/docs/workflows/typescript#messages-arguments

declare const messages: {
  "header": {
    "tools": "Tools",
    "signIn": "Sign in",
    "signUp": "Sign up",
    "languageLabel": "Language",
    "dashboardLabel": "Dashboard",
    "brandTitle": "Your AI Minions",
    "home": "Home",
    "pricing": "Pricing",
    "pointsBadge": "Points 120",
    "pointsWithBalance": "Points {count}",
    "pointsGuestBadge": "Points",
    "pointsGuestHint": "Sign in to see your reward balance",
    "pointsHint": "Reward points balance",
    "signedInAs": "Signed in as",
    "account": "Account",
    "logout": "Logout",
    "openMenu": "Open menu",
    "closeMenu": "Close menu",
    "navigationLabel": "Site navigation"
  },
  "verify": {
    "metaTitle": "Verify email — AI Minions",
    "metaDescription": "Enter the one-time code sent when you signed up.",
    "title": "Confirm your email",
    "subtitle": "Enter the verification code from your inbox. You can sign in with your username or email below.",
    "labelIdentity": "Username or email",
    "placeholderIdentity": "you@example.com",
    "labelOtp": "Verification code",
    "placeholderOtp": "000000",
    "otpHint": "6-digit code from the email we sent you. Check spam if you don’t see it.",
    "submit": "Verify and continue",
    "submitting": "Verifying…",
    "errorTitle": "We couldn’t verify that code",
    "errorOtpExpired": "This code has expired or isn’t valid anymore. Sign up again to get a fresh email, or use the code from the most recent message we sent.",
    "errorOtpWrong": "That code doesn’t match. Copy the six digits from your verification email exactly.",
    "errorGeneric": "Something went wrong. Please try again.",
    "backToSignIn": "Back to sign in",
    "resend": "Resend code by email",
    "resending": "Sending…",
    "resendSuccess": "If your account is waiting for verification, we sent a new code. Check your inbox and spam.",
    "resendWait": "Please wait a bit before requesting another code.",
    "resendNeedIdentity": "Enter your username or email above first.",
    "resendCooldown": "Resend available in {seconds}s"
  },
  "account": {
    "metaTitleProfile": "Account — AI Minions",
    "metaDescriptionProfile": "View and update your profile and contact details.",
    "metaTitlePassword": "Change password — AI Minions",
    "metaDescriptionPassword": "Update your account password securely.",
    "kicker": "Your account",
    "title": "Profile & security",
    "subtitle": "Redeem a membership code, keep your details current, and manage your password.",
    "navLabel": "Account sections",
    "tabProfile": "Profile",
    "tabPassword": "Password",
    "fieldUsername": "Username",
    "fieldEmail": "Email",
    "fieldCredits": "Credits",
    "labelFullname": "Display name",
    "labelPhone": "Phone",
    "save": "Save changes",
    "saving": "Saving…",
    "saved": "Changes saved.",
    "loadError": "Could not load your account.",
    "saveError": "Could not save changes.",
    "notSignedIn": "Session expired. Please sign in again.",
    "passwordHeading": "Change password",
    "passwordHint": "Use at least 6 characters. You will stay signed in on this device.",
    "labelCurrentPassword": "Current password",
    "labelNewPassword": "New password",
    "labelConfirmPassword": "Confirm new password",
    "updatePassword": "Update password",
    "updatingPassword": "Updating…",
    "passwordUpdated": "Password updated.",
    "passwordTooShort": "New password must be at least 6 characters.",
    "passwordMismatch": "New password and confirmation do not match.",
    "passwordError": "Could not update password.",
    "activateTitle": "Redeem membership code",
    "activateSubtitle": "Enter the code you were given to apply your plan and credits to this account.",
    "activateLabel": "Membership code",
    "activatePlaceholder": "Paste your code",
    "activateSubmit": "Apply code",
    "activateSubmitting": "Applying…",
    "activateSuccess": "Your code was applied. Credits and plan access are updated.",
    "activateError": "Could not apply this code."
  },
  "pricing": {
    "metaTitle": "Pricing — AI Minions",
    "metaDescription": "Member plans and credit top-ups for AI Minions. Transparent pricing in MMK.",
    "kicker": "Plans & credits",
    "title": "Simple pricing for serious creators",
    "subtitle": "Choose a membership tier for full studio access, or top up credits whenever you need more runway. All prices in Myanmar Kyat (MMK).",
    "sectionPlans": "Membership tiers",
    "sectionPlansDesc": "Duration-based access with bundled credits — best for steady production.",
    "sectionTopup": "Credit top-ups",
    "sectionTopupDesc": "Add credits without changing your plan — ideal for bursts of work.",
    "bestValue": "Best value",
    "durationLabel": "{days} days access",
    "topupSubtitle": "Credit pack",
    "billedOnce": "One-time purchase",
    "oneTimeCredits": "Credits added to your balance",
    "creditsLine": "{points} credits included",
    "fullStudio": "Full AI studio tools",
    "cta": "Get started",
    "loadError": "We couldn’t load pricing right now. Please try again later.",
    "backHome": "Back to home",
    "emptyPlans": "No membership tiers are published yet.",
    "emptyTopup": "No top-up packs are published yet.",
    "footnote": "Taxes may apply. Features subject to fair use. Contact support for teams."
  },
  "home": {
    "heroTitle": "Create viral-ready videos in a modern AI studio.",
    "heroDescription": "Upload, transcribe, generate, and polish content in one glass-smooth workflow — built for speed and clarity.",
    "getStarted": "Get started",
    "browseTools": "Browse tools",
    "openStudio": "Open Caption Studio",
    "signedInStatus": "Signed in as Creator",
    "allTools": "Workspace tools",
    "available": "Available",
    "openCardLink": "Open tool",
    "toolsPage": {
      "metaTitle": "Workspace tools — AI Minions",
      "metaDescription": "Your dashboard for transcription, captions, voice-over, translation, and the rest of your AI media workflow.",
      "heroTitle": "Your AI media workspace",
      "heroDescription": "Transcribe, caption, generate, and polish from one dashboard — pick a tool below or open Caption Studio to start."
    },
    "overview": {
      "title": "Overview",
      "subtitle": "Today's workspace",
      "live": "Live",
      "items": {
        "captions": {
          "kicker": "Captions",
          "headline": "Viral",
          "description": "Auto captions tuned for short-form hooks and retention."
        },
        "dubbing": {
          "kicker": "Dubbing",
          "headline": "Studio",
          "description": "Voice-over and polish that matches your edit timeline."
        },
        "news": {
          "kicker": "News",
          "headline": "Auto",
          "description": "Turn briefs into ready-to-post updates in one pass."
        }
      }
    },
    "landing": {
      "howItWorks": {
        "title": "How it works",
        "subtitle": "Follow a clear path from upload to finished edit — no guesswork, just the tools you need in order."
      },
      "trust": {
        "title": "Why creators use AI Minions",
        "subtitle": "A focused studio experience with transparent limits and room to grow.",
        "socialProof": "Trusted by 10,000+ creators.",
        "items": {
          "speed": {
            "title": "Fast iteration",
            "description": "Jump between transcription, content, and edits without leaving the workspace."
          },
          "workflow": {
            "title": "One connected flow",
            "description": "Each step hands off cleanly to the next so you spend less time tab-hopping."
          },
          "fairUse": {
            "title": "Credits you understand",
            "description": "See pricing and tiers up front, then use credits where they matter most."
          }
        }
      },
      "faq": {
        "title": "Frequently asked questions",
        "subtitle": "Quick answers about the studio, credits, files, and signing up.",
        "items": {
          "studio": {
            "question": "What is AI Minions?",
            "answer": "AI Minions is an AI-powered media studio for captions, transcription, content generation, voice-over, translation, and video workflows — designed as one cohesive dashboard."
          },
          "credits": {
            "question": "How do credits and plans work?",
            "answer": "You choose a membership tier or top-up pack on the pricing page. Credits apply when you run AI jobs; details and fair-use notes are shown there too."
          },
          "formats": {
            "question": "What files can I upload?",
            "answer": "Video upload accepts common formats like MP4, MOV, and AVI. Clear audio improves transcription quality; check each tool’s tips for the best results."
          },
          "signup": {
            "question": "Do I need an account?",
            "answer": "Yes. Create a free account to save your balance, run tools securely, and access your workspace from any signed-in device."
          }
        }
      },
      "workspaceTools": {
        "subtitle": "Create, edit, and process your videos with AI",
        "dashboardLink": "Open dashboard",
        "recommended": "Recommended",
        "ctaStart": "Start",
        "flow": {
          "leadMark": "↑",
          "steps": {
            "upload": "Upload",
            "transcribe": "Transcribe",
            "translate": "Translate",
            "edit": "Edit",
            "voiceOver": "Voice Over"
          }
        },
        "sections": {
          "startHere": {
            "title": "Start here"
          },
          "process": {
            "title": "Process"
          },
          "createEdit": {
            "title": "Create & edit"
          }
        },
        "descriptions": {
          "viral-shorts": "Upload long-form video and surface viral-ready moments with AI.",
          "video-upload": "Upload your video to begin",
          "transcribe": "Turn video/audio into text",
          "translate": "Translate captions or scripts",
          "video-edit": "Trim and enhance your video",
          "voice-over": "Add AI narration",
          "content-generation": "Create scripts or posts"
        }
      },
      "cta": {
        "title": "Ready to ship your next video?",
        "subtitle": "Create an account, pick a plan when you’re ready, and open any studio tool from the dashboard.",
        "primary": "Create free account",
        "secondary": "View pricing"
      }
    }
  },
  "toolForm": {
    "uploadFile": "Upload file",
    "selectFile": "Select file",
    "clickToUpload": "Click to upload",
    "selectPlaceholder": "Select…",
    "inputText": "Input text",
    "inputTextPlaceholder": "Enter your text here…",
    "processing": "Processing…",
    "run": "Run"
  },
  "result": {
    "title": "Result",
    "fileReady": "Your file is ready to download.",
    "downloadFile": "Download file",
    "downloadDisabled": "(Download disabled in mock mode)"
  },
  "notFound": {
    "title": "404 — Page not found",
    "description": "That tool or page doesn't exist. Check the URL or browse all available tools.",
    "backToHome": "Back to home"
  },
  "themeToggle": {
    "toggleTheme": "Toggle theme"
  },
  "workflow": {
    "heading": "Workflow",
    "tipHeading": "Tip",
    "steps": {
      "viral-shorts": {
        "name": "Viral Shorts",
        "description": "Find clips from long-form video"
      },
      "video-upload": {
        "name": "Video Upload",
        "description": "Upload your video file"
      },
      "transcribe": {
        "name": "Transcribe",
        "description": "Convert speech to text"
      },
      "transcript": {
        "name": "Transcript",
        "description": "Review your transcript"
      },
      "content-generation": {
        "name": "Content Generation",
        "description": "Generate AI content"
      },
      "voice-over": {
        "name": "Voice Over",
        "description": "Add AI narration"
      },
      "video-edit": {
        "name": "Video Edit",
        "description": "Edit and enhance video"
      },
      "admin": {
        "name": "Admin",
        "description": "Manage settings"
      }
    },
    "tips": {
      "viral-shorts": "Use a stable master file (1080p or 4K MP4/WebM). Clear speech and visible subjects help the model pick stronger moments.",
      "video-upload": "Upload MP4, MOV, or AVI files. Clear audio gives the best transcription accuracy.",
      "transcribe": "AI transcription works best with clear audio and minimal background noise.",
      "transcript": "Review and correct the transcript before generating content for better results.",
      "content-generation": "Pick a platform and tone to tailor the generated output to your audience.",
      "voice-over": "Preview voice styles before committing to a full render.",
      "video-edit": "All edits are non-destructive — you can undo any change at any time.",
      "admin": "Manage member tiers, pricing, and user permissions from this dashboard."
    }
  },
  "features": {
    "admin": {
      "name": "Admin",
      "description": "Manage users, pricing, and platform settings."
    },
    "content-generation": {
      "name": "Generate content",
      "description": "Turn ideas into scripts, posts, and marketing copy with AI.",
      "category": "Create content",
      "cardLetter": "C"
    },
    "transcribe": {
      "name": "Convert speech to text",
      "description": "Turn speech in your audio or video into editable text.",
      "category": "Process media",
      "cardLetter": "T"
    },
    "subtitles": {
      "name": "Subtitle generator",
      "description": "Create Myanmar .srt subtitles with timestamps from your audio or video.",
      "category": "Process media",
      "cardLetter": "B"
    },
    "transcript": {
      "name": "Transcript",
      "description": "View and manage your generated transcripts.",
      "category": "Review",
      "cardLetter": "R"
    },
    "video-edit": {
      "name": "Edit video",
      "description": "Trim, adjust, and polish your video in the editor.",
      "category": "Edit & finalize",
      "cardLetter": "E"
    },
    "video-upload": {
      "name": "Upload video",
      "description": "Upload videos to start editing or processing.",
      "category": "Process media",
      "cardLetter": "V"
    },
    "voice-over": {
      "name": "Add voice over",
      "description": "Add natural AI narration to your project.",
      "category": "Create content",
      "cardLetter": "D"
    },
    "translate": {
      "name": "Translate text",
      "description": "Translate scripts and captions into other languages.",
      "category": "Process media",
      "cardLetter": "A"
    },
    "viral-shorts": {
      "name": "Viral Shorts",
      "description": "Turn long videos into vertical 9:16 clips with AI-picked highlights.",
      "category": "Edit & finalize",
      "cardLetter": "S"
    }
  },
  "voice-over": {
    "page": {
      "title": "AI Voice",
      "subtitle": "Convert text into natural-sounding voice"
    },
    "scriptInput": {
      "kicker": "Script",
      "placeholder": "Enter your script here…",
      "example": "Example: Welcome to our channel. Today we will talk about AI tools."
    },
    "generateButton": {
      "label": "Generate Voice",
      "loading": "Generating…"
    },
    "generation": {
      "starting": "Starting voice over…",
      "waitingForUpdates": "Job created. Waiting for updates…",
      "finished": "Finished",
      "errorGeneric": "Voice generation failed. Please try again.",
      "noAudioUrl": "Generation finished but no playable audio was returned."
    }
  },
  "video-edit": {
    "page": {
      "title": "Video Edit",
      "subtitle": "Upload your video to start editing"
    },
    "uploadZone": {
      "label": "Upload your video to start editing",
      "kicker": "Upload video"
    },
    "projects": {
      "title": "My projects",
      "subtitle": "All your video edits in one place",
      "newProject": "New project",
      "stats": {
        "totalProjects": "Total projects",
        "exportedVideos": "Exported videos",
        "storageUsed": "Storage used"
      },
      "recent": "Recent projects",
      "filtersAria": "Filter projects",
      "filters": {
        "all": "All",
        "drafts": "Drafts",
        "exported": "Exported"
      },
      "timeAgo": {
        "twoDays": "2 days ago",
        "oneWeek": "1 week ago",
        "threeDays": "3 days ago"
      },
      "status": {
        "exported": "Exported",
        "processing": "Processing",
        "draft": "Draft"
      },
      "loadMore": "Load more",
      "editProject": "Edit project",
      "deleteProject": "Delete project"
    },
    "workspace": {
      "returnToDashboard": "Return to dashboard",
      "aspectToggleAria": "Canvas aspect ratio",
      "aspect": {
        "ratio16_9": "16:9",
        "ratio9_16": "9:16",
        "ratio1_1": "1:1",
        "ratio4_3": "4:3"
      },
      "exportVideo": "Export video",
      "tools": {
        "media": "media",
        "text": "text",
        "blur": "blur",
        "image": "image",
        "crop": "crop",
        "speed": "speed",
        "subs": "subs",
        "trim": "trim",
        "audio": "audio"
      },
      "tabs": {
        "properties": "properties"
      },
      "font": "Font",
      "position": "Position",
      "opacity": "Opacity",
      "timing": "Timing",
      "timeIn": "in",
      "timeOut": "out",
      "deleteLayer": "Delete layer",
      "subs": {
        "uploadTitle": "Upload .srt file",
        "uploadHint": "Imported captions will be converted to text layers which you can edit freely.",
        "invalidFile": "Please choose a .srt file.",
        "empty": "No subtitles found in this file."
      },
      "canvasAria": "Edit canvas",
      "canvasSampleText": "Hello world",
      "timeAtPlayhead": "{current} / {total}",
      "timeline": {
        "emptyUpload": "Upload a video to see the timeline.",
        "preparing": "Preparing timeline…",
        "tracks": {
          "video": "video",
          "text": "text",
          "blur": "blur",
          "image": "image",
          "subtitle": "subtitle",
          "audio": "audio"
        },
        "clips": {
          "uploadedVideo": "Video",
          "summerReel": "Summer reel.mp4",
          "helloWorld": "Hello world",
          "blurLayer": "Blur layer",
          "autoSubs": "Auto subtitles",
          "backgroundMp3": "background.mp3"
        },
        "trim": {
          "splitAtPlayhead": "Split here",
          "splitAtPlayheadAria": "Divide the video clip at the playhead into two segments; nothing is removed",
          "deleteSegment": "Delete clip",
          "deleteSegmentAria": "Remove the selected video segment from the timeline (requires at least two segments)"
        }
      },
      "playback": {
        "prev": "Previous frame",
        "next": "Next frame",
        "play": "Play",
        "pause": "Pause",
        "speed": "Speed",
        "speedAria": "Playback speed",
        "volume": "Volume",
        "mute": "Mute",
        "unmute": "Unmute",
        "fullscreenEnter": "Enter fullscreen",
        "fullscreenExit": "Exit fullscreen"
      }
    }
  },
  "transcript": {
    "page": {
      "title": "Review Transcript",
      "description": "Review and correct the transcript below before moving to content generation."
    },
    "scriptInput": {
      "placeholder": "Paste or type your transcript here to review and edit…"
    },
    "saveButton": {
      "label": "Save Changes"
    }
  },
  "master-editor": {
    "page": {
      "title": "Master Editor"
    },
    "uploadZone": {
      "label": "Upload your video to start editing"
    },
    "toolbar": {
      "editingTools": "Editing tools",
      "playbackSpeedSection": "Playback speed",
      "addText": "Add text",
      "speedTabHint": "Playback speed is set with the row above. Press play on the preview to hear it.",
      "trim": "Trim",
      "filters": "Filters",
      "adjust": "Adjust",
      "speed": "Speed",
      "text": "Text",
      "trimStart": "Start time",
      "trimEnd": "End time",
      "brightness": "Brightness",
      "contrast": "Contrast",
      "saturation": "Saturation",
      "textPlaceholder": "Overlay text…",
      "position": "Position",
      "positionTop": "Top",
      "positionCenter": "Center",
      "positionBottom": "Bottom",
      "filterNone": "None",
      "filterBw": "B&W",
      "filterWarm": "Warm",
      "filterCool": "Cool",
      "filterVivid": "Vivid"
    },
    "exportPanel": {
      "title": "Export",
      "format": "Format",
      "quality": "Quality",
      "formatSection": "Export format",
      "qualitySection": "Quality",
      "mp4": "MP4",
      "mp4Desc": "Standard video",
      "webm": "WebM",
      "webmDesc": "Web optimized",
      "mov": "MOV",
      "movDesc": "QuickTime",
      "res1080Title": "1080p",
      "res1080Desc": "Full HD",
      "res720Title": "720p",
      "res720Desc": "HD",
      "res480Title": "480p",
      "res480Desc": "SD",
      "export": "Export",
      "exporting": "Exporting…"
    }
  },
  "voice-gen-live": {
    "page": {
      "title": "Voice Gen Live"
    },
    "scriptInput": {
      "placeholder": "Type your script here. Each sentence will be played one by one…"
    },
    "startButton": {
      "label": "Start",
      "playing": "Playing…"
    },
    "livePlayer": {
      "idle": "Idle",
      "playing": "Playing",
      "done": "Done"
    }
  },
  "ai-voice": {
    "page": {
      "title": "AI Voice Generator"
    },
    "scriptInput": {
      "placeholder": "Type or paste the script you want to convert to voice…"
    },
    "generateButton": {
      "label": "Generate Voice",
      "loading": "Generating…"
    }
  },
  "viralShorts": {
    "page": {
      "title": "Viral Shorts",
      "subtitle": "Upload long-form video up to 1 hour 30 min (e.g. podcast, event, interview). AI finds viral moments; trim, preview, download, or combine any two segments into a 9:16 vertical.",
      "helpAria": "Help with Viral Shorts"
    },
    "uploadCard": {
      "title": "Upload long-form video"
    },
    "uploadZone": {
      "instruction": "Click or drop a video (MP4/WebM, max 1 hour 30 min)"
    },
    "continue": {
      "label": "Upload & continue",
      "loading": "Preparing…"
    },
    "analyze": {
      "status": "Video uploaded. Run AI to detect viral moments.",
      "primary": {
        "label": "Analyze for viral clips",
        "loading": "Analyzing…"
      },
      "back": "Back"
    }
  },
  "transcribe": {
    "layout": {
      "previewPlaceholder": "Your audio or video preview will appear here after you choose a file."
    },
    "page": {
      "title": "Transcribe",
      "subtitle": "Convert audio or video to text",
      "helpAria": "Help with transcribe"
    },
    "uploadZone": {
      "label": "Upload your audio or video file",
      "kicker": "Upload audio or video",
      "instruction": "Click to upload or drag and drop",
      "formats": "Video: MP4, WebM, OGG, MOV | Audio: MP3, WAV, OGG, M4A"
    },
    "transcribeButton": {
      "label": "Transcribe to Text",
      "loading": "Transcribing…"
    },
    "transcriptResult": {
      "title": "Transcript",
      "copy": "Copy",
      "copied": "Copied!",
      "download": "Download .txt"
    }
  },
  "subtitlesPage": {
    "hero": {
      "kicker": "Subtitles",
      "description": "Upload an audio or video file to generate a Myanmar .srt with timestamps."
    },
    "uploadZone": {
      "kicker": "Upload",
      "instructionPrimary": "Drop your audio/video file here",
      "instructionSecondary": "We’ll generate an .srt with timestamps"
    },
    "estimate": {
      "loading": "Estimating points…",
      "cost": "Estimated cost: ~{points} points",
      "unavailable": "Estimate unavailable: {message}",
      "prompt": "Select a file to estimate points."
    },
    "generateButton": {
      "label": "Generate subtitles (SRT)",
      "loading": "Generating…"
    },
    "progress": {
      "preparingUpload": "Preparing upload…",
      "uploading": "Uploading…",
      "startingJob": "Starting subtitle job…",
      "finished": "Finished"
    },
    "timeouts": {
      "estimate": "Estimate timed out. Please try again.",
      "prepareUpload": "Prepare upload timed out.",
      "upload": "Upload timed out.",
      "startJob": "Starting job timed out.",
      "preview": "Preview load timed out."
    },
    "errors": {
      "generic": "Something went wrong. Please try again.",
      "sessionExpired": "Your session expired. Please sign in again.",
      "insufficientPoints": "Not enough points to generate subtitles. Please top up and try again.",
      "serviceUnavailable": "Service is temporarily unavailable. Please try again in a moment.",
      "jobFailed": "Subtitle job failed.",
      "generationFailed": "Subtitle generation failed."
    },
    "sse": {
      "subscribed": "Hang tight — we’re generating your subtitles."
    },
    "stages": {
      "download": "Downloading media",
      "extract_audio": "Extracting audio",
      "normalize_audio": "Normalizing audio",
      "segment_audio": "Segmenting audio",
      "ai_subtitles": "Generating subtitles with AI",
      "upload_srt": "Uploading SRT"
    },
    "result": {
      "heading": "Result"
    },
    "download": {
      "title": "Your SRT is ready",
      "description": "Download the generated subtitle file.",
      "button": "Download .srt"
    },
    "preview": {
      "title": "Preview",
      "description": "Quick look at the first cues (timestamps + text). Download the file for the full SRT.",
      "loading": "Loading preview…",
      "truncated": "Preview may be truncated for very large files — download still contains the full SRT.",
      "empty": "No cues parsed for preview."
    }
  },
  "contentGeneration": {
    "page": {
      "title": "Content Creator",
      "subtitle": "Write hooks, captions, and social-ready scripts",
      "helpAria": "Help with content creator"
    },
    "contentTypeLabel": "Content type",
    "contentTypes": {
      "hook": "Hook",
      "caption": "Caption",
      "script": "Script",
      "hashtags": "Hashtags"
    },
    "contentTypeHints": {
      "hook": "Short hooks for TikTok, Reels, and Shorts.",
      "caption": "Social captions, CTAs, and on-screen lines.",
      "script": "Video scripts and narratives.",
      "hashtags": "Trending hashtag stacks for discovery."
    },
    "outputModeLabel": "Output",
    "outputModes": {
      "imageAndText": "Image & text",
      "textOnly": "Text only",
      "imageOnly": "Image only"
    },
    "outputModeHints": {
      "imageAndText": "Get copy plus a visual you can post together.",
      "textOnly": "Scripts, captions, and posts without an image.",
      "imageOnly": "A single image asset from your brief."
    },
    "logoUpload": {
      "kicker": "Brand logo",
      "label": "Upload logo (optional)",
      "instruction": "Click to upload your logo",
      "formats": "PNG, JPG, WEBP, SVG"
    },
    "topicLabel": "Topic or description",
    "topicPlaceholder": "Describe what you want to create content about… Example: A video about AI tools for content creators",
    "toneLabel": "Tone",
    "tones": {
      "engaging": "Engaging",
      "professional": "Professional",
      "casual": "Casual",
      "funny": "Funny",
      "inspiring": "Inspiring",
      "dramatic": "Dramatic"
    },
    "generateButton": {
      "label": "Generate Content",
      "loading": "Generating…"
    },
    "result": {
      "title": "Generated content"
    }
  },
  "translation": {
    "page": {
      "title": "Translate",
      "subtitle": "Multi-language translation for scripts and captions",
      "helpAria": "Help with translation"
    },
    "sourceLanguage": "Source language",
    "targetLanguage": "Target language",
    "sourceText": "Source text",
    "translatedText": "Translated text",
    "sourcePlaceholder": "Enter text to translate…",
    "translatedPlaceholder": "Translation will appear here…",
    "sourceTextStats": "{chars, plural, =0 {0 characters} one {# character} other {# characters}} · {words, plural, =0 {0 words} one {# word} other {# words}}",
    "swap": "Swap",
    "swapAria": "Swap source and target languages and text",
    "action": "Translate",
    "translating": "Translating…",
    "errors": {
      "generic": "Something went wrong. Please try again.",
      "unauthorized": "Your session expired. Please sign in again.",
      "verificationRequired": "Please verify your email to use translation."
    }
  },
  "shared": {
    "uploadZone": {
      "clickToUpload": "Click to upload",
      "dragDrop": "or drag and drop",
      "remove": "Remove file"
    },
    "scriptInput": {
      "characters": "characters"
    },
    "voiceSelector": {
      "label": "Voice style",
      "woman": "Woman",
      "man": "Man",
      "boy": "Boy",
      "girl": "Girl"
    },
    "audioPlayer": {
      "play": "Play",
      "pause": "Pause",
      "download": "Download"
    },
    "loginGate": {
      "defaultMessage": "Sign in to use this feature",
      "signIn": "Sign in"
    }
  },
  "landing": {
    "hero": {
      "headline": "Create Viral Videos in Minutes — No Video Editing Skills Required",
      "subheadline": "AI-powered transcription, captions, voice-overs, and translations. Turn your raw footage into scroll-stopping content.",
      "cta": "Start Free",
      "socialProof": "50,000+ videos processed"
    },
    "problemSolution": {
      "title": "Stop Wasting Time on Manual Work",
      "painPoints": {
        "title": "The Problem",
        "editing": "Editing takes hours",
        "captions": "Captions are tedious",
        "voiceTalent": "Finding voice talent is expensive"
      },
      "solutions": {
        "title": "The Solution",
        "editing": "Spend 10x less time editing",
        "captions": "Auto-generate perfect captions in 50+ languages",
        "voiceTalent": "AI voice-overs for free"
      },
      "howItWorks": {
        "title": "How It Works",
        "step1": "Upload your video",
        "step2": "AI processes (transcribe, translate, generate voice)",
        "step3": "Download ready-to-post content"
      }
    },
    "socialProof": {
      "usersCount": "50,000+ videos processed",
      "rating": "4.8/5 rating",
      "testimonial1": "AI Minions cut my editing time by 80%. I went from 4 hours to 30 minutes per video.",
      "testimonial2": "The auto-caption feature is a game-changer. My TikTok views doubled in a week.",
      "testimonial3": "Finally, a tool that understands creators. The Burmese translation is seamless.",
      "companies": "Trusted by creators at"
    },
    "trust": {
      "freePlan": "Free forever plan",
      "noCard": "No credit card required",
      "secure": "Secure authentication",
      "privacy": "Your data is private"
    },
    "features": {
      "title": "Powerful Features for Creators",
      "captions": {
        "title": "Stop Manual Captioning",
        "description": "Auto-captions in 50+ languages with viral-style formatting",
        "features": ["Auto-captions in 50+ languages", "Viral-style formatting", "One-click SRT export"]
      },
      "dubbing": {
        "title": "Dubbing Made Easy",
        "description": "AI voice generation with 40+ voice options",
        "features": ["AI voice generation", "40+ voice options", "Match video timeline"]
      },
      "translate": {
        "title": "Translate to Any Language",
        "description": "Auto-translate captions to reach global audiences",
        "features": ["Auto-translate captions", "Lip-sync dubbing", "100+ language pairs"]
      },
      "content": {
        "title": "Create Content Faster",
        "description": "Generate scripts, hooks, and captions from topics",
        "features": ["Script generation from topics", "Hook & caption writer", "Hashtag suggestions"]
      }
    },
    "faq": {
      "title": "Frequently Asked Questions",
      "q1": "How much does it cost?",
      "a1": "We offer a free forever plan with no credit card required. Paid plans start from 5,000 MMK/month for extra features.",
      "q2": "How long to set up?",
      "a2": "Sign up takes just 30 seconds. No credit card or installation required.",
      "q3": "Is my content secure?",
      "a3": "Yes, we use enterprise-grade encryption. Your content is stored securely and never shared with third parties.",
      "q4": "Can I cancel anytime?",
      "a4": "Yes, no lock-in contracts. Cancel your plan anytime from your account settings.",
      "q5": "What support is available?",
      "a5": "We offer email and live chat support. Our team typically responds within 2 hours."
    },
    "cta": {
      "getStarted": "Get Started",
      "startFree": "Start Free"
    }
  },
  "footer": {
    "tagline": "AI-powered media creation for everyone",
    "quickLinks": "Quick Links",
    "legal": "Legal",
    "home": "Home",
    "pricing": "Pricing",
    "tools": "Tools",
    "privacy": "Privacy Policy",
    "terms": "Terms of Service",
    "cta": "Start Free",
    "copyright": "© 2024 AI Minions. All rights reserved."
  },
  "tools": {
    "caption-studio": {
      "name": "Caption Studio",
      "description": "Auto-generate captions and subtitles from video files."
    },
    "ai-voice": {
      "name": "AI Voice",
      "description": "Convert text to natural-sounding AI voice audio.",
      "fields": {
        "text": "Text to speak",
        "voice": "Voice style"
      }
    },
    "voice-gen-live": {
      "name": "Voice Gen Live",
      "description": "Real-time voice generation from any text input.",
      "fields": {
        "text": "Text to generate",
        "style": "Style"
      }
    },
    "translate": {
      "name": "Translate",
      "description": "Translate audio or video content into multiple languages.",
      "fields": {
        "targetLanguage": "Target language"
      }
    },
    "content-creator": {
      "name": "Content Creator",
      "description": "Generate social media posts, scripts, and marketing copy.",
      "fields": {
        "prompt": "Describe the content you need",
        "platform": "Platform"
      }
    },
    "story-creator": {
      "name": "Story Creator",
      "description": "Craft compelling story narratives and screenplays with AI.",
      "fields": {
        "premise": "Story premise or prompt",
        "genre": "Genre"
      }
    },
    "srt-sub": {
      "name": "SRT Sub",
      "description": "Generate clean SRT subtitle files directly from video."
    },
    "recapper": {
      "name": "Recapper",
      "description": "Summarize and recap long-form video content automatically."
    },
    "thumbnail": {
      "name": "Thumbnail",
      "description": "Generate eye-catching AI thumbnails for your videos.",
      "fields": {
        "title": "Video title (optional)"
      }
    },
    "novel-translator": {
      "name": "Novel Translator",
      "description": "Translate full novels and long-form documents at scale.",
      "fields": {
        "targetLanguage": "Target language"
      }
    },
    "video-recap": {
      "name": "Video Recap",
      "description": "Create short highlight recap videos from longer footage."
    },
    "master-editor": {
      "name": "Master Editor",
      "description": "AI-powered video editing, cutting, and enhancement."
    },
    "sub-gen": {
      "name": "Sub Gen",
      "description": "Automatically generate burned-in subtitles for any video."
    },
    "transcribe": {
      "name": "Transcribe",
      "description": "Convert speech to accurate, timestamped text transcripts."
    },
    "news-automation": {
      "name": "News Automation",
      "description": "Automate news article and bulletin generation from prompts.",
      "fields": {
        "topic": "News topic or headline",
        "tone": "Tone"
      }
    }
  }
};
export default messages;